name: mobile
description: "Rapid Gana Draw"
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.1
  go_router: ^14.0.2
  intl: any
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
